draft: Feat: Add Callback DataStream
probe-lab/hermes pull request #13
Opened 2024-04-16 06:59 UTC by samcm

- Adds a new `callback` DataStream that implements the `DataStream` interface similar `Kinesis` 
  - Allows other Go projects to start a Hermes `Node` instance directly and to receive events.
  - Unsure if we want to generalize it even further with some config to toggle which `DataStream`'s are enabled. At the moment it's toggled by the existence of aws config.
- Makes the `RpcMeta` structs public for easy consumption in other Go projects
- Added a new type (`EventType`) that contains all event names so it's a little clearer which events are emitted by Hermes
  - Missing `REQUEST_` events since these haven't been traced in `main` yet
  - Edge case with events derived from the `beacon` topic string - some events might slip through the cracks.
  - Was considering adding concrete types for entire events but unsure if that was wanted. Regardless, can be added in the future.
  - Definitely not a requirement - can remove

Related Xatu integration: https://github.com/ethpandaops/xatu/pull/297

2024-05-14 11:37 UTC, guillaumemichel reviewed
Looks good to me so far. @cortze may also want to provide a review as he may be more familiar with the implementation.

@samcm let us know here once the PR is ready :)

2024-05-27 05:12 UTC, samcm commented
Thanks @guillaumemichel! This one is ready for review I think. I've testing it against a localstack Kinesis and it looked ok but I've never really used Kinesis before so not entirely sure what to test against. I could produce/consume messages at least. cc @cortze 🙏

2024-05-29 16:34 UTC, cortze requested changes
LGTM! I was able to run it, and it was submitting traces to AWS Kinesis without any problem. 

I can take care of anything missing if needed :)

2024-05-29 16:34 UTC, cortze commented on host/kinesis.go
> +
`staticcheck` doesn't seem to be happy with this `timeoutCncl`, this should make the tests happy
```suggestion
	timeoutCncl()
```

2024-06-03 01:13 UTC, samcm commented
Should be all good now @cortze, thank you!

2024-06-03 07:14 UTC, cortze approved these changes

2024-06-03 07:18 UTC, merged